apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: eureka-server
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: eureka-server
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:
  source:
    git:
      url: https://github.com/gowthamshankar99/spring-order-service-.git
      ref:
        branch: main
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17.*"